### ISSUE TITLE
Unable to use a passphrase at start

### ISSUE THREAD

**Issue by stricaud** [DCSO/MISP-dockerized-proxy#17]
I would like to be able to add a simple "ssl.passphrase" in the config/ directory so it is copied and used by a directive such as ssl_password_file, as documented in
http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_password_file

**Comment by stricaud** [comment]
This is my actual workaround, patching this on both misp-proxy and misp-server. I write that here to help the maintainer and anyone searching the web for a solution:
In a Makefile, or type line by line, whatever you prefer.

```
patch-ssl-passphrase:
        -docker cp misp-proxy:/etc/nginx/conf.d/SERVER_HTTPS_and_redirected_HTTP.conf .
        -grep ssl_password_file SERVER_HTTPS_and_redirected_HTTP.conf || awk '{if ($$1 ~ /ssl_certificate_key/) { print $$0 "\n\tssl_password_file /etc/nginx/ssl/ssl.passphrase\n";} else { print $$0 };}' < SERVER_HTTPS_and_redirected_HTTP.conf > SERVER\
_HTTPS_and_redirected_HTTP.newconf
        -mv SERVER_HTTPS_and_redirected_HTTP.newconf SERVER_HTTPS_and_redirected_HTTP.conf
        -docker cp SERVER_HTTPS_and_redirected_HTTP.conf misp-proxy:/etc/nginx/conf.d/
        -docker cp misp-proxy:/etc/nginx/conf.d/SERVER_MAINTENANCE .
        -grep ssl_password_file SERVER_MAINTENANCE.conf || awk '{if ($$1 ~ /ssl_certificate_key/) { print $$0 "\n\tssl_password_file /etc/nginx/ssl/ssl.passphrase\n";} else { print $$0 };}' < SERVER_MAINTENANCE.conf > SERVER_MAINTENANCE.newconf
        -mv SERVER_MAINTENANCE.newconf SERVER_MAINTENANCE.conf
        -docker cp SERVER_MAINTENANCE.conf misp-proxy:/etc/nginx/conf.d/
        -docker cp ssl.passphrase misp-proxy:/etc/nginx/ssl/
        -docker cp ssl-apache-dialog.sh misp-server:/etc/apache2/ssl/
        -docker cp misp-server:/etc/apache2/sites-enabled/misp.ssl.conf .
        -awk '!found && /<VirtualHost/ { print "SSLPassPhraseDialog exec:/etc/apache2/ssl/ssl-apache-dialog.sh\n"; found=1 } 1' misp.ssl.conf > misp.newssl
        -mv misp.newssl misp.ssl.conf
        -docker cp misp.ssl.conf misp-server:/etc/apache2/sites-enabled/
        -docker restart misp-server
        -docker restart misp-proxy
```

Here the content of /etc/apache2/ssl/ssl-apache-dialog.sh:
```
#!/bin/bash
echo "mys3cr3tPASSPHRASE"
```

**Comment by 8ear** [comment]
Hi @stricaud,
sorry for my late respond. I have overlooked the notification.
I will try to build in your use case in the new container 1.6 and MISP-dockerized major version 1.2.0

**Comment by 8ear** [comment]
Do want to add your passphrase via file or via Environment variable?

**Comment by stricaud** [comment]
via file is perfect for me, but actually I don't care of the method, as long as it is documented and there is a way :)

**Comment by 8ear** [comment]
There is the documentation:
https://dcso.github.io/MISP-dockerized-docs/admin/ssl_passphrase.html
But I need to improve it. :-)
I prefer the method via environment variable. But I added also the file variant.

**Comment by 8ear** [comment]
I close the issue now with the hint to https://github.com/DCSO/MISP-dockerized-proxy/pull/18 and https://github.com/DCSO/MISP-dockerized/pull/70
